### ISSUE TITLE
Post Dropdown Sub Menu is misaligned

### ISSUE THREAD

**Issue by kaakaa** [mattermost/mattermost-plugin-demo#101]
## Summary
Since submenu is misaligned, it's hard to select a submenu.

![スクリーンショット 2020-05-01 22 43 56](https://user-images.githubusercontent.com/1453749/80809834-81452300-8bfd-11ea-999f-db31aa1e170c.png)

## Environment
* **Mattermost**: v5.22.0 
* **Plugin**: master branch (c49f9517d593e092a76b0a5742a150374c78c2c1)
* **Browser**: Chrome, Safari

**Comment by jfrerich** [comment]
Hi @kaakaa!  Thanks for posting this issue.  I'll set priority to get this fixed. It would provide a better to declutter the pulldown when lots of plugins are installed.  It's also hard to access the submenus as it currently stands

**Comment by hanzei** [comment]
@jfrerich Do you know if this issue is causes by the demo plugin or the webapp? If it's the later, would you mind creating a JIRA?

**Comment by aaronrothschild** [comment]
I can't get the Demo plugin to run on my cloud server :(. it keeps crashing.

**Comment by jfrerich** [comment]
@hanzei I believe this is a webapp issue.  I'll post as a Jira ticket

**Comment by jfrerich** [comment]
Jira ticket created https://mattermost.atlassian.net/browse/MM-26644

**Comment by hanzei** [comment]
@kaakaa Are you interested on working on this?

**Comment by hanzei** [comment]
Closing per https://mattermost.atlassian.net/browse/MM-26644?focusedCommentId=103633
