### ISSUE TITLE
Cant build demo

### ISSUE THREAD

**Issue by AG-Labs** [mattermost/mattermost-plugin-demo#113]
I have tried to build this demo on both windows and centos and am getting failures.

On windows i assume it is my make command because Centos get furthers but on Centos when running make it fails due to the permissions on WriteFile being greater than 0600. I would have thought running make on the repo as it is on master should build correctly.

Am I missing something?

**Comment by hanzei** [comment]
What exactly is the error that you seeing on Centos?

**Comment by AG-Labs** [comment]
> What exactly is the error that you seeing on Centos?

I am seeing the following error for the server when the make file is run.


`golangci-lint run ./...
build/manifest/main.go:127:13: G306: Expect WriteFile permissions to be 0600 or less (gosec)
                if err := ioutil.WriteFile(
                        "server/manifest.go",
                        []byte(fmt.Sprintf(pluginIDGoFileTemplate, manifestStr)),
                        0644,
                ); err != nil {
build/manifest/main.go:147:13: G306: Expect WriteFile permissions to be 0600 or less (gosec)
                if err := ioutil.WriteFile(
                        "webapp/src/manifest.js",
                        []byte(fmt.Sprintf(pluginIDJSFileTemplate, manifestStr)),
                        0644,
                ); err != nil {
make: *** [golangci-lint] Error 1
`

**Comment by hanzei** [comment]
`make dist` does build the plugin without running the linter.

**Comment by AG-Labs** [comment]
Yeah Centos is happy building with `make dist`. I assume the linting rules have just changed.

**Comment by hanzei** [comment]
@AG-Labs Are you still having issue building the plugin on Windows?

**Comment by AG-Labs** [comment]
Since I got it working with make dost on centos I did not move back to the windows machine

**Comment by hanzei** [comment]
Would you be fine if I close this ticket then?

**Comment by AG-Labs** [comment]
Yeah if we assume it was an issue with the windows setup I was provided and not a wide spread issue
