### ISSUE TITLE
FileWillBeUploaded does not implement the server hook 

### ISSUE THREAD

**Issue by agarciamontoro** [mattermost/mattermost-plugin-demo#125]
The `FileWillBeUploaded` hook in [file_hooks.go](https://github.com/mattermost/mattermost-plugin-demo/blob/master/server/file_hooks.go) is never called by the server, as it does not implement the function defined by the interface.

The plugin's function signature is:
```go
FileWillBeUploaded(c *plugin.Context, fileInfo *model.FileInfo, reader bytes.Reader, buf *bytes.Buffer)
```

but the one defined in [the interface](https://github.com/mattermost/mattermost-server/blob/master/plugin/hooks.go#L193) is:

```go
FileWillBeUploaded(c *Context, info *model.FileInfo, file io.Reader, output io.Writer) (*model.FileInfo, string)
```

We need to change the signature to match the one defined by the interface and check that it actually gets called when a file is uploaded.

**Comment by yash2189** [comment]
@agarciamontoro I am new to opensource , I just wanted to ask whether we need to change the plugin function signature same as the one defined in the interface?

**Comment by agarciamontoro** [comment]
Hi @yash2189, welcome! 

> I just wanted to ask whether we need to change the plugin function signature same as the one defined in the interface and then check whether it's executing properly?

Yes, that's exactly what we need! When changing the function signature to match the one defined in the interface, there will be some things in the function body that we will need to change, too.

Do you want to give it a try?

**Comment by yash2189** [comment]
Yes but it might some time for me , will that be ok? As I need to setup the environment on my local machine and help regarding the same.It might not be possible for me to complete during Hacktoberfest

**Comment by agarciamontoro** [comment]
There is no rush at all, take all the time you need! And feel free to ask any questions, either here or in Mattermost: maybe the [~Toolkit](https://community-daily.mattermost.com/core/channels/developer-toolkit) channel is the best place to ask (feel free to mention me there, too).

**Comment by yash2189** [comment]
Sure @agarciamontoro I will start from 31st October will that be ok?

**Comment by agarciamontoro** [comment]
Absolutely!

**Comment by haardikdharma10** [comment]
Hey @agarciamontoro, if this issue is still available, I'd like to give this one a shot.

**Comment by agarciamontoro** [comment]
Hi @haardikdharma10! @yash2189 is still working on this issue, so it's not available for the moment, sorry! But feel free to take a look at [the open issues](https://github.com/mattermost/mattermost-server/issues?q=is%3Aissue+is%3Aopen+label%3A%22Help+Wanted%22++label%3A%22Up+For+Grabs%22), I'm sure you'll find something you want to work on! Thank you for your interest in contributing :pray:

**Comment by agarciamontoro** [comment]
@adithyaakrishna, I see you already opened a PR. Are you still unsure on what to do here?
