### ISSUE TITLE
Demo plugin minimum version seems to have changed

### ISSUE THREAD

**Issue by DHaussermann** [mattermost/mattermost-plugin-demo#128]
There seems to be an issue with the new Demo plugin release `0.9.0` 

When doing release testing for 5.29 - I noticed the plugin will not start.
Logs show: `"Unable to activate plugin","plugin_id":"com.mattermost.demo-plugin","error":"this plugin requires Mattermost v5.30.0 or later"}`

When looking at the releases page, I see 5.26.0 listed as the minimum version still.

**Comment by DHaussermann** [comment]
@hanzei to your knowledge, was there an intentional change to the min version or is something else happening here?

**Comment by hanzei** [comment]
That was done intentionally. I fixed the required server version on the release page. Closing.
